source 'https://github.com/CocoaPods/Specs.git'

target 'Falcon', :exclusive => true do
  pod "Falcon", :path => "../"
  pod 'MRProgress/Overlay', '~> 0.8'
end

target 'Tests', :exclusive => true do
  pod "Falcon", :path => "../"  
end
