source 'https://github.com/CocoaPods/Specs.git'

target 'Falcon', :exclusive => true do
  pod "Falcon", :path => "../"
  pod 'Mantle', '~> 1.5'
end

target 'Tests', :exclusive => true do
  pod "Falcon", :path => "../"  
end
